### ISSUE TITLE
Resources.pb.cc 初始化不存在导致编译失败

### ISSUE THREAD

**Issue by rover12421** [lizhangqu/aapt-cmake-buildscript#1]
`buildscript/aapt2_static/CMakeLists.txt` 中的配置：
```
#生成的文件在这个目录
        ${CMAKE_SOURCE_DIR}/frameworks/base/tools/aapt2/frameworks/base/tools/aapt2/Resources.pb.cc
        ${CMAKE_SOURCE_DIR}/frameworks/base/tools/aapt2/frameworks/base/tools/aapt2/ResourcesInternal.pb.cc
```
有问题，代码同步之后，这两个文件实际是不存在的，需要先注释这两行，然后执行
```
cmake --build "./build-cmake" --target protobuffer_h -- -j 8
```
才会有。

**Comment by lizhangqu** [comment]
这两个文件是protobuffer生成的文件，不需要注释，在编译aapt2之前，将对应头文件生成即可

```
cmake --build "./build-cmake" --target protobuffer_h -- -j 8
```

生成完毕后，将cmake进行reload（clion在File->Reload cmake project），命令行直接使用cmake重新生成构建文件，之后就能正常构建aapt2了。

如果在cmake文件生成及配置阶段，报了这两个文件不存在，调用命令将其生成即可，目前没有十分好的办法自动化解决这个问题，主要是因为没有找到cmake对应的方式，如果您有更好的方法，还原提供pr。
