### ISSUE TITLE
能不能添加arm的交叉编译

### ISSUE THREAD

**Issue by rover12421** [lizhangqu/aapt-cmake-buildscript#2]
希望能添加arm的交叉编译支持！！！

**Comment by lizhangqu** [comment]
交叉编译的支持，主要有两点：
   - 编写cmake的toolchain
   - 配置对应的arm交叉编译工具链环境

cmake toolchain的编写可参看：

[windows.toolchain.cmake](https://github.com/lizhangqu/aapt-cmake-buildscript/blob/android-8.1.0_r1/windows.toolchain.cmake)

交叉编译环境的生成可参看：

[Mac 生成 Linux 交叉编译工具链](http://fucknmb.com/2017/08/18/Mac%E7%94%9F%E6%88%90Linux%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91%E5%B7%A5%E5%85%B7%E9%93%BE/)，配置生成arm的环境即可

个人精力有限，目前仅维护mac，linux(ubuntu or centos)及windows x86和x86_64版本，如果您有时间，欢迎提出pr，当然也不排除后续提供arm版本的编译
  
更加简单的方法是直接在arm的宿主机上直接编译，比如建个虚拟机
