### ISSUE TITLE
可以添加整个build-tools编译的cmake脚本吗

### ISSUE THREAD

**Issue by ghost** [lizhangqu/aapt-cmake-buildscript#3]
我在手机上安通过proot的方式安装了arm64的ubuntu，然后我自己编译了一个arm64的NDK，现在就差一个sdk了，不知道你能提供下android-sdk下build-tools的完整cmake脚本么，比如aidl,，zipalign,，dex，dx，……

**Comment by lizhangqu** [comment]
@hiliuzhiyong 源码级编译吧
