### ISSUE TITLE
cmake --build "./build-cmake" --target protobuffer_h -- -j 8 执行错误

### ISSUE THREAD

**Issue by fengruisd** [lizhangqu/aapt-cmake-buildscript#4]
你好，请教一下，
执行   cmake --build "./build-cmake" --target protobuffer_h -- -j 8   的时候，报下面的错误，请问如何可以解决？

error: unknown warning option '-Wno-user-defined-warnings'; did you mean
      '-Wno-user-defined-literals'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-user-defined-warnings'; did you mean
      '-Wno-user-defined-literals'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-user-defined-warnings'; did you mean
      '-Wno-user-defined-literals'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-user-defined-warnings'; did you mean
      '-Wno-user-defined-literals'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-user-defined-warnings'; did you mean
      '-Wno-user-defined-literals'? [-Werror,-Wunknown-warning-option]
make[3]: *** [buildscript/protobuf/aprotoc/CMakeFiles/aprotoc.dir/__/__/__/external/protobuf/src/google/protobuf/descriptor.pb.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [buildscript/protobuf/aprotoc/CMakeFiles/aprotoc.dir/__/__/__/external/protobuf/src/google/protobuf/any.cc.o] Error 1
make[3]: *** [buildscript/protobuf/aprotoc/CMakeFiles/aprotoc.dir/__/__/__/external/protobuf/src/google/protobuf/extension_set.cc.o] Error 1
make[3]: *** [buildscript/protobuf/aprotoc/CMakeFiles/aprotoc.dir/__/__/__/external/protobuf/src/google/protobuf/descriptor_database.cc.o] Error 1
make[3]: *** [buildscript/protobuf/aprotoc/CMakeFiles/aprotoc.dir/__/__/__/external/protobuf/src/google/protobuf/descriptor.cc.o] Error 1
error: error: unknown warningunknown  optionwarning  '-Wno-user-defined-warnings';option did  '-Wno-user-defined-warnings';you  didmean 
you       '-Wno-user-defined-literals'?mean 
[-Werror,-Wunknown-warning-option]      '-Wno-user-defined-literals'?
 [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-user-defined-warnings'; did you mean
      '-Wno-user-defined-literals'? [-Werror,-Wunknown-warning-option]
make[3]: *** [buildscript/protobuf/aprotoc/CMakeFiles/aprotoc.dir/__/__/__/external/protobuf/src/google/protobuf/dynamic_message.cc.o] Error 1
make[3]: *** [buildscript/protobuf/aprotoc/CMakeFiles/aprotoc.dir/__/__/__/external/protobuf/src/google/protobuf/arena.cc.o] Error 1
make[3]: *** [buildscript/protobuf/aprotoc/CMakeFiles/aprotoc.dir/__/__/__/external/protobuf/src/google/protobuf/arenastring.cc.o] Error 1
make[2]: *** [buildscript/protobuf/aprotoc/CMakeFiles/aprotoc.dir/all] Error 2

**Comment by lizhangqu** [comment]
-Wno-unknown-warning-option
